### ISSUE TITLE
Wood Treatment macro not following the recipe

### ISSUE THREAD

**Issue by Asnath1** [DashingStrike/Automato-ATITD11#177]
The recipe I inputed in treat_board.txt shows correctly on screen, but then macro only applies 10 sec of each ingredients...
(eg not following quantities in the recipe)

[Wood trt](https://github.com/DashingStrike/Automato-ATITD11/assets/29504721/05996e57-8b6c-4e9e-90a9-71f79392903e)
[treat_boards.txt](https://github.com/DashingStrike/Automato-ATITD11/files/14331096/treat_boards.txt)

**Comment by atitdMacPhisto** [comment]
This has been determined to be a side-effect of the AZERTY keyboard layout. The current workaround is to enable CAPS LOCK since SHIFT is required to enter a number.
